version: "3.11"
services:

  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DB_URI=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}
    command: bash ./start_server.sh
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGUSER: ${DATABASE_USERNAME}
      PGDATABASE: ${DATABASE_NAME}
      PGPASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5432}:5432
    restart: always

volumes:
  db_data:
