version: "3.11"
services:
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379
    environment:
      - REDISCLI_AUTH=${REDIS_PASSWORD:-redis_pass}
    command: >
      --requirepass ${REDIS_PASSWORD:-redis_pass}

  worker:
    build: .
    image: 270968290167.dkr.ecr.eu-west-2.amazonaws.com/fmc-backend:latest
    restart: always
    env_file:
      - .env
    environment:
      - DB_URI=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis
    command: bash start_worker.sh
    depends_on:
      - db
      - redis

  app:
    build: .
    image: 270968290167.dkr.ecr.eu-west-2.amazonaws.com/fmc-backend:latest
    restart: always
    env_file:
      - .env
    environment:
      - DB_URI=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis
    command: bash start_server.sh
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
      - worker

  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGUSER: ${DATABASE_USERNAME}
      PGDATABASE: ${DATABASE_NAME}
      PGPASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:${DATABASE_LOCAL_PORT:-5432}:5432
    restart: always

  backup:
    build: pg-backup/
    image: 270968290167.dkr.ecr.eu-west-2.amazonaws.com/fmc-db-backup
    restart: always
    volumes:
      - ./backup:/backup
    links:
      - db
    environment:
      SCHEDULE: "@daily"
      POSTGRES_DATABASE: ${DATABASE_NAME}
      POSTGRES_HOST: db
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_EXTRA_OPTS: "--schema=public --blobs"
      DAYS_HISTORY: 7

volumes:
  db_data:
