"""schedule booking

Revision ID: 108bc01f04bc
Revises: c02feb49c881
Create Date: 2023-04-10 16:20:21.005091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108bc01f04bc'
down_revision = 'c02feb49c881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_schedules', sa.Column('is_booked', sa.Boolean(), nullable=True))
    op.drop_column('coach_schedules', 'reccurence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_schedules', sa.Column('reccurence', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('coach_schedules', 'is_booked')
    # ### end Alembic commands ###