"""empty message

Revision ID: 1514c0a906cf
Revises: afec4892dc53
Create Date: 2023-03-16 15:34:22.360992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1514c0a906cf'
down_revision = 'afec4892dc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sport_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coaches', sa.Column('about', sa.String(length=1024), nullable=True))
    op.add_column('coaches', sa.Column('certificate_url', sa.String(length=256), nullable=True))
    op.add_column('coaches', sa.Column('is_for_adults', sa.Boolean(), nullable=True))
    op.add_column('coaches', sa.Column('is_for_children', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('street', sa.String(length=64), nullable=True))
    op.add_column('locations', sa.Column('postal_code', sa.String(length=64), nullable=True))
    op.drop_column('locations', 'address_line_2')
    op.drop_column('locations', 'address_line_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address_line_1', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('address_line_2', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('locations', 'postal_code')
    op.drop_column('locations', 'street')
    op.drop_column('coaches', 'is_for_children')
    op.drop_column('coaches', 'is_for_adults')
    op.drop_column('coaches', 'certificate_url')
    op.drop_column('coaches', 'about')
    op.drop_table('sport_skills')
    op.drop_table('coaches_locations')
    # ### end Alembic commands ###