"""profiles

Revision ID: 226b37dbb868
Revises: c36e94f12826
Create Date: 2023-03-23 15:25:48.408740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226b37dbb868'
down_revision = 'c36e94f12826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_uuid'), 'certificates', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_uuid'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###