"""schedule

Revision ID: 41e9b9025a2a
Revises: c09fa80b2255
Create Date: 2023-04-04 15:37:39.845533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41e9b9025a2a'
down_revision = 'c09fa80b2255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_schedules', sa.Column('begin_hours', sa.Integer(), nullable=False))
    op.add_column('coach_schedules', sa.Column('begin_minutes', sa.Integer(), nullable=False))
    op.add_column('coach_schedules', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('coach_schedules', 'begin')
    op.drop_column('coach_schedules', 'end')
    op.drop_column('coach_schedules', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_schedules', sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('coach_schedules', sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('coach_schedules', sa.Column('begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('coach_schedules', 'duration')
    op.drop_column('coach_schedules', 'begin_minutes')
    op.drop_column('coach_schedules', 'begin_hours')
    # ### end Alembic commands ###