"""empty message

Revision ID: 485564c0cf2b
Revises: b5955e23ce2f
Create Date: 2023-03-21 12:45:50.865636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '485564c0cf2b'
down_revision = 'b5955e23ce2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'appointment_time')
    op.drop_column('lessons', 'date')
    op.add_column('students_lessons', sa.Column('appointment_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('students_lessons', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students_lessons', 'date')
    op.drop_column('students_lessons', 'appointment_time')
    op.add_column('lessons', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('appointment_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###