"""empty message

Revision ID: 54409e3da46d
Revises: ffe9739e6364
Create Date: 2023-03-17 15:34:44.251364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54409e3da46d'
down_revision = 'ffe9739e6364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_skills')
    op.alter_column('coaches', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.add_column('messages', sa.Column('text', sa.String(length=1024), nullable=False))
    op.add_column('messages', sa.Column('author_id', sa.String(length=36), nullable=False))
    op.add_column('messages', sa.Column('receiver_id', sa.String(length=36), nullable=False))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('messages', 'message_to')
    op.drop_column('messages', 'message_from')
    op.drop_column('messages', 'created_at_timestamp')
    op.drop_column('messages', 'message_text')
    op.alter_column('students', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.add_column('messages', sa.Column('message_text', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('created_at_timestamp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('message_from', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('message_to', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'author_id')
    op.drop_column('messages', 'text')
    op.alter_column('coaches', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_table('sport_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('sport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport_types.id'], name='sport_skills_sport_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sport_skills_pkey')
    )
    # ### end Alembic commands ###