"""newsletters

Revision ID: 58bb18448adf
Revises: c36e94f12826
Create Date: 2023-03-23 16:11:13.994989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58bb18448adf"
down_revision = "c36e94f12826"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "state", sa.Enum("NEW", "ACTIVE", "CANCELED", name="state"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("newsletter_subscriptions")
    # ### end Alembic commands ###
