"""add to coach profile experience and credentials

Revision ID: 6cd16f588cd3
Revises: 2a003833ebd1
Create Date: 2023-04-14 10:16:57.184983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd16f588cd3'
down_revision = '2a003833ebd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('experience', sa.String(length=1024), nullable=True))
    op.add_column('coaches', sa.Column('credentials', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'credentials')
    op.drop_column('coaches', 'experience')
    # ### end Alembic commands ###