"""empty message

Revision ID: 7363b969c812
Revises: 290c5c816324
Create Date: 2023-03-02 18:29:46.420373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7363b969c812'
down_revision = '290c5c816324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches_sports', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('coaches_sports', 'amount')
    op.drop_column('coaches_sports', 'created_at')
    op.drop_column('locations', 'created_at')
    op.add_column('sport_types', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('sport_types', 'created_at')
    op.drop_column('sport_types', 'sport_types_enum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_types', sa.Column('sport_types_enum', postgresql.ENUM('volleyball', 'box', 'tennis', 'swimming', name='sporttypes'), autoincrement=False, nullable=True))
    op.add_column('sport_types', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('sport_types', 'name')
    op.add_column('locations', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('coaches_sports', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('coaches_sports', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('coaches_sports', 'price')
    # ### end Alembic commands ###