"""add to package additional information

Revision ID: 7a11657e06ae
Revises: 6cd16f588cd3
Create Date: 2023-04-14 12:41:36.667924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a11657e06ae'
down_revision = '6cd16f588cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('additional_information_title', sa.String(length=512), nullable=True))
    op.add_column('lessons', sa.Column('additional_information_description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'additional_information_description')
    op.drop_column('lessons', 'additional_information_title')
    # ### end Alembic commands ###