"""empty message

Revision ID: 9a2ff4a65a89
Revises: 2e3ffdc95079
Create Date: 2023-04-04 18:03:12.293381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2ff4a65a89'
down_revision = '2e3ffdc95079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_schedules', sa.Column('week_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_schedules', 'week_day')
    # ### end Alembic commands ###