"""contact_request

Revision ID: a198e91210b7
Revises: 9906bae2af23
Create Date: 2023-03-07 18:11:43.304114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a198e91210b7'
down_revision = '9906bae2af23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email_from', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('have_replied', sa.Boolean(), nullable=True),
    sa.Column('in_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###