"""empty message

Revision ID: b5955e23ce2f
Revises: ea40e7ded3a5
Create Date: 2023-03-21 11:33:33.783598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5955e23ce2f'
down_revision = 'ea40e7ded3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###