"""stripe_id

Revision ID: c02feb49c881
Revises: 66ea8056140c
Create Date: 2023-04-06 15:58:33.891234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02feb49c881'
down_revision = '66ea8056140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('stripe_customer_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'stripe_customer_id')
    # ### end Alembic commands ###