"""likes

Revision ID: c09fa80b2255
Revises: 6fa6c86d1c74
Create Date: 2023-03-30 17:59:19.829351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c09fa80b2255"
down_revision = "6fa6c86d1c74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_favourite_coaches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=True),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_favourite_coaches")
    # ### end Alembic commands ###
