"""empty message

Revision ID: c33740a56a91
Revises: 5d79bc3fa7ac
Create Date: 2023-03-29 14:12:04.539788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33740a56a91'
down_revision = '5d79bc3fa7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_lessons', sa.Column('review_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students_lessons', 'review_id')
    # ### end Alembic commands ###