"""empty message

Revision ID: d5cb284aa96e
Revises: 522d36d1b70f
Create Date: 2023-03-20 11:16:17.734967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cb284aa96e'
down_revision = '522d36d1b70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaches', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('students', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('coaches', 'profile_picture',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###