"""notes to coach schedule

Revision ID: ea40e7ded3a5
Revises: c36e94f12826
Create Date: 2023-03-21 11:25:36.267433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea40e7ded3a5'
down_revision = 'c36e94f12826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_schedules', sa.Column('notes', sa.String(length=256), nullable=True))
    op.drop_constraint('lessons_student_id_fkey', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lessons_student_id_fkey', 'lessons', 'students', ['student_id'], ['id'])
    op.drop_column('coach_schedules', 'notes')
    # ### end Alembic commands ###