"""empty message

Revision ID: eaf679276b41
Revises: 10fbb6fe9e99
Create Date: 2023-03-24 12:41:51.635927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf679276b41'
down_revision = '10fbb6fe9e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=32), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('unit_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stripe_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=64), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['stripe_product_prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coach_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('current_period_end', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['stripe_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coaches', sa.Column('stripe_customer_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'stripe_customer_id')
    op.drop_table('coach_subscriptions')
    op.drop_table('stripe_products')
    op.drop_table('stripe_product_prices')
    # ### end Alembic commands ###