"""certificate is_deleted

Revision ID: f2ff9a8c5987
Revises: 10fbb6fe9e99
Create Date: 2023-03-27 08:21:55.377913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ff9a8c5987'
down_revision = '10fbb6fe9e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'is_deleted')
    # ### end Alembic commands ###