"""messages

Revision ID: ffe9739e6364
Revises: 1514c0a906cf
Create Date: 2023-03-16 22:13:53.711046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe9739e6364'
down_revision = '1514c0a906cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('message_text', sa.String(length=1024), nullable=False),
    sa.Column('message_from', sa.String(length=36), nullable=False),
    sa.Column('message_to', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at_timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_uuid'), 'coaches', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaches_uuid'), table_name='coaches')
    op.drop_table('messages')
    # ### end Alembic commands ###